version: "3.1"

services:
  postgres-liquibase:
    container_name: postgres-liquibase
    image: liquibase/liquibase
    command: --defaultsFile=liquibase.properties update
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
      - ./config/liquibase.properties:/liquibase/liquibase.properties
    networks:
      - postgres-net
networks:
  postgres-net: