version: "3.1"

services:
  ms-sql-liquibase:
    container_name: ms-sql-liquibase
    image: liquibase/liquibase
    command: --url=jdbc:sqlserver://ms-sql-db:1433;username=sa;password=Passw0rd!?2223 --changeLogFile=changelog.xml update
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
    networks:
      - ms-sql-net
networks:
  ms-sql-net:  