name: Build Action

on:
    push:
      paths:
        - 'DataAccess/DataAccess.Repository/**'
        - 'DataAccess/Extensions/DataAccess.Repository.HotChocolate/**'
        jobs:
            build:
              runs-on: ubuntu-latest
              steps:
                - name: Debug
                  run: echo "Hello, debugging!"