name: Build Action

on:
    push:
      paths:
        - 'DataAccess/DataAccess.Repository/**'
        - 'DataAccess/Extensions/DataAccess.Repository.HotChocolate/**'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
          project: ['DataAccess.Repository', 'DataAccess.Repository.HotChocolate']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    # Set up local NuGet repo
    - name: Setup GitHub NuGet
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Ian-Webster/index.json"

    # Resource NuGet dependencies
    - name: Restore dependencies
      run: dotnet restore 'DataAccess/${{ matrix.project }}'        

    # Build project
    - name: Build
      run: dotnet build --configuration Release 'DataAccess/${{ matrix.project }}'