on:
    push:
      paths:
        - 'DataAccess.Repository/'
        - 'Extensions/DataAccess.Repository.HotChocolate/'
jobs:
    debug:
      runs-on: ubuntu-latest
      steps:
        - name: Debug Paths
          run: |
            echo "Files in repository:"
            ls -R
            echo "Changed files in this push:"
            git diff --name-only ${{ github.event.before }} ${{ github.sha }}
  